name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Deploy to Compute
        uses: fastly/compute-actions@v12
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
