name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_dispatch || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-wasip1
      - name: Deploy to Compute
        uses: fastly/compute-actions@v13
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
